#!/bin/bash

# Test script for webhook

file_name="$1"

curl --tlsv1 -k -X POST \
	  -H "Content-Type: application/json" \
	  -H "Cache-Control: no-cache" \
	  -d "$file_name" "https://localhost:9090/RMINOLBOT"
